### ISSUE TITLE
Deposito no se aparece en en el historial 

### ISSUE THREAD

**Issue by tobiasrivera** [Menexve/MenexExchange#2]
Que tal equipo Menex exito por su iniciativa muy practica la apliacacion pero temo indicarles que al generar un deposito entre cuentas no se muestra en el historial, todo esto lo lleve a cabo en la Billetera.

![image](https://user-images.githubusercontent.com/42784753/44750893-b45c1880-aae4-11e8-8cb7-a583f1265f58.png)

**Comment by chiguireitor** [comment]
Ya el equipo de desarrollo del engine está al tanto, en cuanto lo resolvamos vamos a estar dando respuesta por esta vía.
