### ISSUE TITLE
Añadir Mas Bancos

### ISSUE THREAD

**Issue by Jose9219** [Menexve/MenexExchange#7]
Me gusta la pagina pero no estan los bancos donde se hagan los depositos y transferencias asi que les pido que agregen el BANCO DE VENEZUELA. POR FAVOR

**Comment by Menexve** [comment]
Buenas tardes.

Estimado Jose, gusto en saludarte, una vez te registres e ingreses en nuestra plataforma podrás encontrar la lista de los bancos disponibles y los detalles para las transferencias. Ya iniciamos operaciones formalmente y contamos por ahora con dos (2) operadores financieros para llevar a cabo los depositos en BsS. Actualmente se está en proceso de apertura de cuentas en otras entidades bancarias, por lo que en los próximos días tendremos más bancos a tu disposición.

Saludos.
